"""
This code generates plots to compare results presented in the paper by Jiang (arXiv:2206.12425).
The focus is on the evolution of central/core density profiles derived from two methods:
the 'Isothermal' method (R1-procedure) and the 'Gravothermal' simulation.

All necessary data are stored in the directory: `Data_Extraction`.
All plots generated by this code should be stored in the directory: `Results`.

We perform this analysis using the specific parameters chosen in the publication, as follows:

1) Halo mass: M_vir = 10**9.89 [M_sun]
2) Dark Matter concentration: c = 15.8 [dimensionless]
3) Cross-section: sigma/m = 5 [cm^2/g]

Additionally, we note an unusual discrepancy:

4) The gravothermal parameter: beta = 0.75, used in the publication, corresponds to beta = 1.12
   in our gravothermal simulation. This difference suggests potential variations in the implementation
   of the gravothermal simulation between Jiang's approach and ours.
"""
import os
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
# --- IMPORT FROM FILES
import GravothermalData as gravoF
import RprocedureData as rprocF
import units as uni
import auxiliaryFunctions as aux

# ##################################### SETTINGS ##################################### #
plot_save = True
output_plot_dir = "Results"

# --- the base directory will be our directory
OUR_DIR = os.path.dirname(os.path.abspath(__file__))

# --- select gravothermal directory
# gravothermal
DATA_GRAVOTHERMAL = os.path.join(OUR_DIR, 'Data_Extraction')
# isothermal
DATA_ISOTHERMAL_NFW_LoDen_DIR = os.path.join(OUR_DIR, 'Data_Extraction')
DATA_ISOTHERMAL_NFW_HiDen_DIR = os.path.join(OUR_DIR, 'Data_Extraction')

# --- select files:
gravothermal_file_1 = 'ρsol_M_10.1_t_10.0_sigma_0.008_beta_0.75.txt'
gravothermal_file_2 = 'σsol_M_10.1.txt'
# gravothermal_file_2 = 'ρσ_sol_M_9.89_t_175_sigma_5.0_beta_1.1.csv'
# gravothermal_file_3 = 'ρσ_sol_M_9.89_t_175_sigma_5.0_beta_1.0.csv'

# print(df_Pippin['t-hat'])
# print(df_Pippin['rho-hat'])

# ##################################### SET DATA TO CLASS ############################################################ #
# ------------------------------- GRAVOTHERMAL ------------------------------- #
# --- file with beta = 0.75
gravoEvolution_1 = gravoF.create_gravothermalData_from_file(gravothermal_file_1, DATA_GRAVOTHERMAL, beta=0.75)
# put the name to differentiate data in class (what initial profile is)
gravoEvolution_1.put_the_name("NFW")

# --- file with beta = 1.1
gravoEvolution_2 = gravoF.create_gravothermalData_from_file(gravothermal_file_2, DATA_GRAVOTHERMAL, beta=0.75)
# put the name to differentiate data in class (what initial profile is)
gravoEvolution_2.put_the_name("NFW")


# ##################################### PLOTTING COMPARISON ########################################################## #
def apply_log_scale_grid(_ax):
    """
    Apply grid and log scale settings to a Matplotlib axis.

    Parameters:
        _ax (matplotlib.axes.Axes): The axis to which the settings will be applied.
    """
    # Grid settings
    _ax.grid(which='minor', alpha=0.2)
    _ax.grid(which='major', alpha=0.4)

    # Log-scale tick marks for x-axis
    locmaj_x = mticker.LogLocator(base=10, numticks=12)
    locmin_x = mticker.LogLocator(base=10.0,
                                  subs=(0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9),
                                  numticks=12)
    _ax.xaxis.set_major_locator(locmaj_x)
    _ax.xaxis.set_minor_locator(locmin_x)
    _ax.xaxis.set_minor_formatter(mticker.NullFormatter())

    # Log-scale tick marks for y-axis
    locmaj_y = mticker.LogLocator(base=10, numticks=12)
    locmin_y = mticker.LogLocator(base=10.0,
                                  subs=(0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9),
                                  numticks=12)
    _ax.yaxis.set_major_locator(locmaj_y)
    _ax.yaxis.set_minor_locator(locmin_y)
    _ax.yaxis.set_minor_formatter(mticker.NullFormatter())

    # Tick length and direction
    _ax.tick_params('both', direction='in', top=True, right=True, length=10,
                    width=1, which='major', zorder=301)
    _ax.tick_params('both', direction='in', top=True, right=True, length=5,
                    width=1, which='minor', zorder=301)

# ------------------ PLOT: Scaling-beta-parameter ------------------------------------- #
fig, ax = plt.subplots(figsize=(11.0, 7.0))
# log scale
ax.set_xscale('log')
ax.set_yscale('log')
# describe plot
plt.ylim(10 ** 0, 2 * 10 ** 3)
plt.ylabel(r'$\hat{\rho} = \rho/\rho_{s}$', fontsize=18)
plt.xlabel(r'$\hat{t} = t \cdot \left( \frac{4}{\sqrt{\pi}} \sigma_{\mathrm{m}} \rho_s \nu_{0}\right)$', fontsize=18)
plt.title(r'Rescale $\beta$ parameter', fontsize=18)
ax.tick_params(labelsize=14)

# Apply the log scale and grid settings
apply_log_scale_grid(ax)

# --- DATA
# The evolution of core density for gravothermal simulation, beta = 1.1
gravo_time_l, gravo_rho_l = gravoEvolution_2.return_rho_core_evolution(elements=2)
ax.plot(uni.time_tilda(gravo_time_l, rho_s, r_s, sigma_m), gravo_rho_l,
        label=f'Gravothermal $\\beta$: {gravoEvolution_2.beta}')
plt.axvline(x=uni.time_tilda(time_collapse_2, rho_s, r_s, sigma_m), linestyle=':', color='grey',
            label=f'Collapse time: {"{:.3f}".format(uni.time_tilda(time_collapse_2, rho_s, r_s, sigma_m))}, refers to '
            f'{"{:.3f}".format(time_collapse_2)} [Gyr].')
# The evolution of core density for gravothermal simulation, beta = 1.0
gravo_time_l, gravo_rho_l = gravoEvolution_3.return_rho_core_evolution(elements=2)
ax.plot(uni.time_tilda(gravo_time_l, rho_s, r_s, sigma_m), gravo_rho_l,
        label=f'Gravothermal $\\beta$: {gravoEvolution_3.beta}')
plt.axvline(x=uni.time_tilda(time_collapse_3, rho_s, r_s, sigma_m), linestyle=':', color='black',
            label=f'Collapse time: {"{:.3f}".format(uni.time_tilda(time_collapse_3, rho_s, r_s, sigma_m))}, refers to '
            f'{"{:.3f}".format(time_collapse_3)} [Gyr].')

# --- LEGEND AND SAVE
ax.legend(fontsize=14)
if plot_save is True:
    plt.savefig('./' + output_plot_dir + '/' + 'Scaling-beta-parameter' + '.png', dpi=300)
else:
    plt.show()

# ------------------ PLOT: CENTRAL DENSITY (ISO) AND CORE DENSITY (GRAVO): JIANG ------------------------------------- #
fig, ax = plt.subplots(figsize=(11.0, 7.0))
# log scale
ax.set_xscale('log')
ax.set_yscale('log')
# describe plot
plt.ylim(10 ** 0, 2 * 10 ** 3)
plt.ylabel(r'$\hat{\rho} = \rho/\rho_{s}$', fontsize=18)
plt.xlabel(r'$\hat{t} = t \cdot \left( \frac{4}{\sqrt{\pi}} \sigma_{\mathrm{m}} \rho_s \nu_{0}\right)$', fontsize=18)
plt.title(r'Jiang: Gravothermal vs Isothermal', fontsize=18)
ax.tick_params(labelsize=14)

# Apply the log scale and grid settings
apply_log_scale_grid(ax)

# --- DATA
# The evolution of core density for gravothermal simulation, beta = 0.75
gravo_time_l, gravo_rho_l = gravoEvolution_1.return_rho_core_evolution(elements=2)
ax.plot(uni.time_tilda(gravo_time_l, rho_s, r_s, sigma_m), gravo_rho_l,
        label=f'Gravothermal $\\beta$: {gravoEvolution_1.beta}')
# The evolution of core density for gravothermal simulation, beta = 1.1
gravo_time_l, gravo_rho_l = gravoEvolution_2.return_rho_core_evolution(elements=2)
ax.plot(uni.time_tilda(gravo_time_l, rho_s, r_s, sigma_m), gravo_rho_l,
        label=f'Gravothermal $\\beta$: {gravoEvolution_2.beta} (their $\\beta: 0.75$)')
plt.axvline(x=uni.time_tilda(time_collapse_2, rho_s, r_s, sigma_m), linestyle=':', color='grey',
            label=f'Collapse time: {"{:.3f}".format(uni.time_tilda(time_collapse_2, rho_s, r_s, sigma_m))}, refers to '
            f'{"{:.3f}".format(time_collapse_2)} [Gyr].')

# The evolution of central density for R-procedure simulation: JIANG
iso_lowDen_central_time_l, iso_lowDen_central_rho_l = isoEvolution_Jiang['LoDen'].return_central_rho()
ax.plot(uni.time_tilda(iso_lowDen_central_time_l, rho_s, r_s, sigma_m), iso_lowDen_central_rho_l,
        '--', label='Isothermal (low dense): Jiang')
iso_HigDen_central_time_l, iso_HigDen_central_rho_l = isoEvolution_Jiang['HiDen'].return_central_rho()
ax.plot(uni.time_tilda(iso_HigDen_central_time_l, rho_s, r_s, sigma_m), iso_HigDen_central_rho_l,
        '--', label='Isothermal (high dense): Jiang')
# --- Jiang tmerge
ax.scatter(uni.time_tilda(jiangIsoParameters["time-end"], rho_s, r_s, sigma_m),
           isoEvolution_Jiang['LoDen'].central_data['rho'][jiangTimeSteps - 1],
           marker='*', s=90.0, zorder=3,
           label=f'tmerge: {"{:.3f}".format(uni.time_tilda(jiangIsoParameters["time-end"], rho_s, r_s, sigma_m))}, refers to '
                 f'{"{:.3f}".format(jiangIsoParameters["time-end"])} [Gyr].',
           facecolor='red', edgecolor='black', linewidth=1.0, rasterized=True)
# --- LEGEND AND SAVE
ax.legend(fontsize=14)
if plot_save is True:
    plt.savefig('./' + output_plot_dir + '/' + 'Jiang-Gravothermal-vs-Isothermal' + '.png', dpi=300)
else:
    plt.show()


# ------------------ PLOT: CENTRAL DENSITY (ISO) AND CORE DENSITY (GRAVO) -------------------------------------------- #
fig, ax = plt.subplots(figsize=(11.0, 7.0))
# log scale
ax.set_xscale('log')
ax.set_yscale('log')
# describe plot
plt.ylim(10 ** 0, 2 * 10 ** 3)
plt.ylabel(r'$\hat{\rho} = \rho/\rho_{s}$', fontsize=18)
plt.xlabel(r'$\hat{t} = t \cdot \left( \frac{4}{\sqrt{\pi}} \sigma_{\mathrm{m}} \rho_s \nu_{0}\right)$', fontsize=18)
plt.title(r'Full comparison', fontsize=18)
ax.tick_params(labelsize=14)

# Apply the log scale and grid settings
apply_log_scale_grid(ax)

# --- DATA
# The evolution of core density for gravothermal simulation, beta = 0.75
gravo_time_l, gravo_rho_l = gravoEvolution_1.return_rho_core_evolution(elements=2)
ax.plot(uni.time_tilda(gravo_time_l, rho_s, r_s, sigma_m), gravo_rho_l,
        label=f'Gravothermal $\\beta$: {gravoEvolution_1.beta}.')
# The evolution of core density for gravothermal simulation, beta = 1.1
gravo_time_l, gravo_rho_l = gravoEvolution_2.return_rho_core_evolution(elements=2)
ax.plot(uni.time_tilda(gravo_time_l, rho_s, r_s, sigma_m), gravo_rho_l,
        label=f'Gravothermal $\\beta$: {gravoEvolution_2.beta}.')
plt.axvline(x=uni.time_tilda(time_collapse_2, rho_s, r_s, sigma_m), linestyle=':', color='grey',
            label=f'Collapse time: {"{:.3f}".format(uni.time_tilda(time_collapse_2, rho_s, r_s, sigma_m))}, refers to '
            f'{"{:.3f}".format(time_collapse_2)} [Gyr].')

# The evolution of central density for R-procedure simulation: OUR
iso_lowDen_central_time_l, iso_lowDen_central_rho_l = isoEvolution_our['LoDen'].return_central_rho()
ax.plot(uni.time_tilda(iso_lowDen_central_time_l, rho_s, r_s, sigma_m), iso_lowDen_central_rho_l,
        '-.', label='Isothermal (low dense): our')
iso_HigDen_central_time_l, iso_HigDen_central_rho_l = isoEvolution_our['HiDen'].return_central_rho()
ax.plot(uni.time_tilda(iso_HigDen_central_time_l, rho_s, r_s, sigma_m), iso_HigDen_central_rho_l,
        '-.', label='Isothermal (high dense): our')
# The evolution of central density for R-procedure simulation: JIANG
iso_lowDen_central_time_l, iso_lowDen_central_rho_l = isoEvolution_Jiang['LoDen'].return_central_rho()
ax.plot(uni.time_tilda(iso_lowDen_central_time_l, rho_s, r_s, sigma_m), iso_lowDen_central_rho_l,
        '--', label='Isothermal (low dense): Jiang')
iso_HigDen_central_time_l, iso_HigDen_central_rho_l = isoEvolution_Jiang['HiDen'].return_central_rho()
ax.plot(uni.time_tilda(iso_HigDen_central_time_l, rho_s, r_s, sigma_m), iso_HigDen_central_rho_l,
        '--', label='Isothermal (high dense): Jiang')

# --- LEGEND AND SAVE
ax.legend(fontsize=14, loc='upper left')
if plot_save is True:
    plt.savefig('./' + output_plot_dir + '/' + 'Comparison-to-Figure-6' + '.png', dpi=300)
else:
    plt.show()

# ------------------ PLOT: CENTRAL DENSITY (ISO): OUR VS JIANG -------------------------------------------- #
fig, ax = plt.subplots(figsize=(11.0, 7.0))
# log scale
ax.set_xscale('log')
ax.set_yscale('log')
# describe plot
plt.ylim(10 ** 0, 2 * 10 ** 3)
plt.ylabel(r'$\hat{\rho} = \rho/\rho_{s}$', fontsize=18)
plt.xlabel(r'$\hat{t} = t \cdot \left( \frac{4}{\sqrt{\pi}} \sigma_{\mathrm{m}} \rho_s \nu_{0}\right)$', fontsize=18)
plt.title(r'Isothermal: Us vs Jiang', fontsize=18)
ax.tick_params(labelsize=14)

# Apply the log scale and grid settings
apply_log_scale_grid(ax)

# --- DATA
# The evolution of central density for R-procedure simulation: OUR
iso_lowDen_central_time_l, iso_lowDen_central_rho_l = isoEvolution_our['LoDen'].return_central_rho()
ax.plot(uni.time_tilda(iso_lowDen_central_time_l, rho_s, r_s, sigma_m), iso_lowDen_central_rho_l,
        '-.', label='Isothermal (low dense): our')
iso_HigDen_central_time_l, iso_HigDen_central_rho_l = isoEvolution_our['HiDen'].return_central_rho()
ax.plot(uni.time_tilda(iso_HigDen_central_time_l, rho_s, r_s, sigma_m), iso_HigDen_central_rho_l,
        '-.', label='Isothermal (high dense): our')
# The evolution of central density for R-procedure simulation: JIANG
iso_lowDen_central_time_l, iso_lowDen_central_rho_l = isoEvolution_Jiang['LoDen'].return_central_rho()
ax.plot(uni.time_tilda(iso_lowDen_central_time_l, rho_s, r_s, sigma_m), iso_lowDen_central_rho_l,
        '--', label='Isothermal (low dense): Jiang')
iso_HigDen_central_time_l, iso_HigDen_central_rho_l = isoEvolution_Jiang['HiDen'].return_central_rho()
ax.plot(uni.time_tilda(iso_HigDen_central_time_l, rho_s, r_s, sigma_m), iso_HigDen_central_rho_l,
        '--', label='Isothermal (high dense): Jiang')

# --- our tmerge
ax.scatter(uni.time_tilda(ourIsoParameters["time-end"], rho_s, r_s, sigma_m),
           isoEvolution_our['LoDen'].central_data['rho'][ourTimeSteps - 1],
           marker='o', s=50.0, zorder=3,
           label=f'tmerge: {"{:.3f}".format(uni.time_tilda(ourIsoParameters["time-end"], rho_s, r_s, sigma_m))}, which refers to '
                 f'{"{:.3f}".format(ourIsoParameters["time-end"])} [Gyr].',
           facecolor='grey', edgecolor='black', linewidth=1.0, rasterized=True)

# --- Jiang tmerge
ax.scatter(uni.time_tilda(jiangIsoParameters["time-end"], rho_s, r_s, sigma_m),
           isoEvolution_Jiang['LoDen'].central_data['rho'][jiangTimeSteps - 1],
           marker='*', s=90.0, zorder=3,
           label=f'tmerge: {"{:.3f}".format(uni.time_tilda(jiangIsoParameters["time-end"], rho_s, r_s, sigma_m))}, which refers to '
                 f'{"{:.3f}".format(jiangIsoParameters["time-end"])} [Gyr].',
           facecolor='red', edgecolor='black', linewidth=1.0, rasterized=True)

# --- Pippin simulation
ax.scatter(df_Pippin['t-hat'], df_Pippin['rho-hat'],
           marker="v", s=50.0, zorder=3,
           label=f'cosmological sim Pippin',
           facecolor='blue', edgecolor='black', linewidth=1.0, rasterized=True)


# --- LEGEND AND SAVE
ax.legend(fontsize=14)
if plot_save is True:
    plt.savefig('./' + output_plot_dir + '/' + 'Jiang-vs-Us-Isothermal-with-markers' + '.png', dpi=300)
else:
    plt.show()

# ------------------ PLOT: CENTRAL DENSITY (ISO): OUR VS JIANG -------------------------------------------- #
fig, ax = plt.subplots(figsize=(11.0, 7.0))
# log scale
ax.set_xscale('log')
ax.set_yscale('log')
# describe plot
plt.ylim(10 ** 0, 2 * 10 ** 3)
plt.ylabel(r'$\hat{\rho} = \rho/\rho_{s}$', fontsize=18)
plt.xlabel(r'$\hat{t} = t \cdot \left( \frac{4}{\sqrt{\pi}} \sigma_{\mathrm{m}} \rho_s \nu_{0}\right)$', fontsize=18)
plt.title(r'Isothermal: Us vs Jiang', fontsize=18)
ax.tick_params(labelsize=14)

# Apply the log scale and grid settings
apply_log_scale_grid(ax)

# --- DATA
# The evolution of central density for R-procedure simulation: OUR
iso_lowDen_central_time_l, iso_lowDen_central_rho_l = isoEvolution_our['LoDen'].return_central_rho()
ax.plot(uni.time_tilda(iso_lowDen_central_time_l, rho_s, r_s, sigma_m), iso_lowDen_central_rho_l,
        '-.', label='Isothermal (low dense): our')
iso_HigDen_central_time_l, iso_HigDen_central_rho_l = isoEvolution_our['HiDen'].return_central_rho()
ax.plot(uni.time_tilda(iso_HigDen_central_time_l, rho_s, r_s, sigma_m), iso_HigDen_central_rho_l,
        '-.', label='Isothermal (high dense): our')
# The evolution of central density for R-procedure simulation: JIANG
iso_lowDen_central_time_l, iso_lowDen_central_rho_l = isoEvolution_Jiang['LoDen'].return_central_rho()
ax.plot(uni.time_tilda(iso_lowDen_central_time_l, rho_s, r_s, sigma_m), iso_lowDen_central_rho_l,
        '--', label='Isothermal (low dense): Jiang')
iso_HigDen_central_time_l, iso_HigDen_central_rho_l = isoEvolution_Jiang['HiDen'].return_central_rho()
ax.plot(uni.time_tilda(iso_HigDen_central_time_l, rho_s, r_s, sigma_m), iso_HigDen_central_rho_l,
        '--', label='Isothermal (high dense): Jiang')

# --- LEGEND AND SAVE
ax.legend(fontsize=14)
if plot_save is True:
    plt.savefig('./' + output_plot_dir + '/' + 'Jiang-vs-Us-Isothermal' + '.png', dpi=300)
else:
    plt.show()
